name: Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: scrapealicious/scrapealicious/docs   
        build-command: make html

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: scrapealicious/scrapealicious/docs/_build/html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: scrapealicious/scrapealicious/docs/_build/html

    - name: List contents of _build/html
      run: ls -R scrapealicious/scrapealicious/docs/_build/html

